[1012]
id = "1012"
level = "INFO"
msg = "Conectado con exito a SQL Server"
module_func = "servicios_sql.py-> ServiciosSql._conectar()"

[1013]
id = "1013"
level = "ERROR"
msg = "No se pudo conectar a la bese de datos."
module_func = "servicios_sql.py-> ServiciosSql._conectar()"

[1014]
id = "1014"
level = "INFO"
msg = "ConexiÃ³n cerrada a la base de datos."
module_func = "servicios_sql.py-> ServiciosSql._desconectar()"

[1015]
id = "1015"
level = "INFO"
msg = "Consultando a la BD, DataFrame obtenido."
module_func = "servicios_sql.py-> ServiciosSql.consultar()"

[1016]
id = "1016"
level = "ERROR"
msg = "Error al consultar al realizar la consulta."
module_func = "servicios_sql.py-> ServiciosSql._consultar()"

[1017]
id = "1017"
level = "INFO"
msg = "Comando ejecutado en la base de datos."
module_func = "servicios_sql.py-> ServiciosSql._ejecutar()"

[1018]
id = "1018"
level = "ERROR"
msg = "Ocurrio un error al ejecutar el comando en la base de datos."
module_func = "servicios_sql.py-> ServiciosSql._ejecutar()"

[1019]
id = "1019"
level = "INFO"
msg = "Se obtubo la informacion de los clientes activos en el portal."
module_func = "models.py-> ConsultasManejador._consultar_clientes_portal()"

[1020]
id = "1020"
level = "Error"
msg = "Ocurrio un error los clientes activos en el portal."
module_func = "models.py-> ConsultasManejador._consultar_clientes_portal()"